export const loginStyle = {
  form: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
    marginTop: '50px',
    width: '384px',
  },
  input: {
    width: '100%',
    height: '44px',
    boxSizing: 'border-box',
    padding: '0 12px',
    border: '1px solid #d7d7d7',
    borderRadius: '4px',
    fontSize: '16px',
  },
  inputFocus: {
    border: '2px solid #54a7da',
    outline: 'none',
  },
  inputbutton: {
    width: '384px',
    height: '44px',
    cursor: 'pointer',
    background: 'black',
    color: 'white',
    fontSize: '18px',
    fontWeight: 'bold',
    border: 'none',
  },
  autoLoginWrapper: {
    display: 'flex',
    alignItems: 'center',
    height: 'auto',
    gap: '8px',
  },
  autoLoginLabel: {
    fontSize: '14px',
    color: '#575757',
  },
  checkbox: {
    appearance: 'none',
    WebkitAppearance: 'none',
    width: '20px',
    height: '20px',
    padding: 0,
    flexShrink: 0,
    border: '1px solid #d7d7d7',
    borderRadius: '4px',
    backgroundColor: '#fff',
    cursor: 'pointer',
    outline: 'none',
  },
  join: {
    display: 'flex',
    fontSize: '16px',
    position: 'absolute',
    bottom: '30px',
    left: '50%',
    transform: 'translateX(-50%)',
    color: '#666',
  },
  joinSpan: {
    textDecoration: 'underline',
    fontSize: '16px',
    cursor: 'pointer',
  },
};
 